"""Add steam ID formats

Revision ID: 02397d5db1b8
Revises: 
Create Date: 2025-04-18 15:37:16.838086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02397d5db1b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id64', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('steam_id3', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('steam_profile_url', sa.Text(), nullable=True))
        batch_op.drop_index('ix_users_steam_id')
        batch_op.create_index(batch_op.f('ix_users_steam_id64'), ['steam_id64'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_steam_id64'))
        batch_op.create_index('ix_users_steam_id', ['steam_id'], unique=1)
        batch_op.drop_column('steam_profile_url')
        batch_op.drop_column('steam_id3')
        batch_op.drop_column('steam_id64')

    # ### end Alembic commands ###
